SELECT nombre AS nom FROM producto ORDER BY Nom ASC;
SELECT nombre AS Nom, precio AS Preu FROM producto ORDER BY Nom ASC;
DESCRIBE producto;
SELECT nombre AS Nom, precio AS 'Preu en €', ROUND(precio*0.97,2) AS 'Preu en $' FROM producto;
SELECT nombre AS 'nom de producto', precio AS 'euros', ROUND(precio*0.97,2) AS 'dòlars' FROM producto;
SELECT UPPER(nombre), precio FROM producto;
SELECT LOWER(nombre), precio FROM producto;
SELECT fabricante.nombre AS 'Nom del Fabricant', UPPER(LEFT(nombre,2)) FROM fabricante;
SELECT nombre AS 'Nom', ROUND(precio) AS 'Preu arrodonit' FROM producto;
SELECT nombre AS 'Nom', TRUNCATE(precio,0) AS 'Preu truncat' FROM producto;
SELECT codigo_fabricante AS 'Codi del Fabricant' FROM producto;
SELECT DISTINCT(codigo_fabricante) AS 'Codi del Fabricant' FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre AS 'Nom' FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 2 OFFSET 3;
SELECT nombre AS 'Nom', precio AS 'Preu' FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre AS 'Nom', precio AS 'Preu' FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre AS 'Nom del producte' FROM producto WHERE codigo_fabricante=2;
SELECT producto.nombre AS 'Nom del producte', precio AS 'Preu', fabricante.nombre AS 'Nom del fabricant' FROM producto JOIN fabricante ON codigo_fabricante=fabricante.codigo;
SELECT producto.nombre AS 'Nom del producte', precio AS 'Preu', fabricante.nombre AS 'Nom del fabricant' FROM producto JOIN fabricante ON codigo_fabricante=fabricante.codigo ORDER BY fabricante.nombre ASC;